### ISSUE TITLE
Maven warning 'repositories.repository.id' must not be 'local'

### ISSUE THREAD

**Issue by yepher** [NiceSystems/hrider#31]
When building the project I get the warning shown below. Can just rename "local" to "localrepo" to get rid of that warning?

[hrider (master)]$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for h-rider:h-rider:jar:1.0.5.0
[WARNING] 'repositories.repository.id' must not be 'local', this identifier is reserved for the local repository, using it for other repositories will corrupt your repository metadata. @ line 17, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by vdere** [comment]
how

**Comment by avandenberghe** [comment]
it means the .m2/settings.xml has an incorrect <pluginRepository> <id> reference.
